import csv
import psycopg2
from faker import Faker
import random

# Initialize Faker with an Indian locale for realistic names and numbers
fake = Faker('en_IN')

# Database connection parameters (Connecting through your Kubernetes tunnel)
DB_HOST = "127.0.0.1"
DB_PORT = "5432"
DB_NAME = "sos_db"
DB_USER = "sos_admin"
DB_PASS = "admin123"

def seed_database():
    print("Connecting to the Kubernetes database...")
    conn = psycopg2.connect(
        host=DB_HOST, port=DB_PORT, dbname=DB_NAME, user=DB_USER, password=DB_PASS
    )
    cur = conn.cursor()

    print("Enabling PostGIS spatial engine...")
    cur.execute("CREATE EXTENSION IF NOT EXISTS postgis;")

    print("Building tables...")
    
    # 1. Users Table
    cur.execute("""
        CREATE TABLE IF NOT EXISTS users (
            user_id VARCHAR(50) PRIMARY KEY,
            full_name VARCHAR(100),
            blood_type VARCHAR(10),
            medical_conditions TEXT,
            emergency_contact VARCHAR(20)
        );
    """)

    # 2. Facilities Table (Notice the GEOMETRY column for the map coordinates)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS emergency_facilities (
            id SERIAL PRIMARY KEY,
            osm_id VARCHAR(50),
            name VARCHAR(255),
            amenity_type VARCHAR(50),
            contact_number VARCHAR(50),
            location GEOMETRY(Point, 4326)
        );
    """)

    # 3. Active Alerts Table (Set up for your sequential dispatch logic)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS active_alerts (
            alert_id UUID PRIMARY KEY,
            user_id VARCHAR(50) REFERENCES users(user_id),
            status VARCHAR(50),
            facility_id INT REFERENCES emergency_facilities(id),
            timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    """)

    print("Generating 50 realistic user profiles...")
    blood_types = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-']
    conditions = ['None', 'Asthma', 'Type 1 Diabetes', 'Hypertension', 'Penicillin Allergy', 'None', 'None']
    
    for i in range(1, 51):
        user_id = f"usr_{i:03d}"
        name = fake.name()
        b_type = random.choice(blood_types)
        med = random.choice(conditions)
        phone = fake.phone_number()
        
        cur.execute(
            "INSERT INTO users (user_id, full_name, blood_type, medical_conditions, emergency_contact) VALUES (%s, %s, %s, %s, %s) ON CONFLICT DO NOTHING;",
            (user_id, name, b_type, med, phone)
        )

    print("Loading OpenStreetMap facilities from CSV...")
    try:
        with open('facilities.csv', 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Extracting the exact columns generated by Overpass Turbo
                osm_id = row.get('@id', '')
                name = row.get('name', 'Unknown Facility')
                amenity = row.get('amenity', 'unknown')
                phone = row.get('contact:phone', 'Not Available')
                
                # Safety check in case of blank rows
                if not row.get('@lat') or not row.get('@lon'):
                    continue
                    
                lat = float(row.get('@lat'))
                lon = float(row.get('@lon'))

                # Critical PostGIS rule: Longitude always comes before Latitude in ST_MakePoint!
                cur.execute("""
                    INSERT INTO emergency_facilities (osm_id, name, amenity_type, contact_number, location)
                    VALUES (%s, %s, %s, %s, ST_SetSRID(ST_MakePoint(%s, %s), 4326))
                """, (osm_id, name, amenity, phone, lon, lat))
                
    except FileNotFoundError:
        print("Error: facilities.csv not found! Make sure it is in the same folder as seed.py.")
        return

    # Save all changes and close the connection
    conn.commit()
    cur.close()
    conn.close()
    print("Database successfully seeded and ready for the API!")

if __name__ == "__main__":
    seed_database()